# Generated by Django 5.2.17 on 2026-09-23 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('excerpt', models.TextField()),
                ('content', models.TextField()),
                ('cover_image', models.CharField(max_length=500)),
                ('author', models.CharField(default='Spirit Adventure Team', max_length=100)),
                ('category', models.CharField(default='Trekking Guides', max_length=100)),
                ('reading_time_minutes', models.PositiveIntegerField(default=5)),
                ('meta_title', models.CharField(blank=True, max_length=150)),
                ('meta_description', models.CharField(blank=True, max_length=250)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icon', models.CharField(default='Mountain', help_text='Icon identifier e.g. Mountain, Tent, Waves, Snowflake, Sun, Users', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('cover_image', models.CharField(help_text='Image URL or public path', max_length=500)),
                ('hero_image', models.CharField(blank=True, help_text='Large banner image URL', max_length=500)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(default='Mountains', help_text='e.g. Mountains, Lakes, Camping, Treks, Sunrises', max_length=100)),
                ('image_url', models.CharField(max_length=500)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ordering', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('full_description', models.TextField()),
                ('duration_days', models.PositiveIntegerField(default=1)),
                ('duration_nights', models.PositiveIntegerField(default=0)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MODERATE', 'Moderate'), ('CHALLENGING', 'Challenging'), ('DIFFICULT', 'Difficult')], default='MODERATE', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Current starting price in INR', max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original price for discount strikethrough', max_digits=10, null=True)),
                ('pickup_location', models.CharField(default='Dehradun / Base Camp', max_length=150)),
                ('drop_location', models.CharField(default='Dehradun / Base Camp', max_length=150)),
                ('altitude', models.CharField(blank=True, help_text='e.g. 12,500 ft / 3,810 m', max_length=100)),
                ('trek_distance', models.CharField(blank=True, help_text='e.g. 20 km total', max_length=100)),
                ('best_season', models.CharField(default='Dec - Apr', max_length=150)),
                ('cover_image', models.CharField(help_text='Main landscape photo URL', max_length=500)),
                ('hero_video_url', models.CharField(blank=True, help_text='Optional nature video link (.mp4 or embed)', max_length=500)),
                ('inclusions', models.JSONField(blank=True, default=list, help_text="List of strings e.g. ['All meals on trek', 'Tented accommodation']")),
                ('exclusions', models.JSONField(blank=True, default=list, help_text="List of strings e.g. ['Transport to base camp', 'Personal porter']")),
                ('things_to_carry', models.JSONField(blank=True, default=list, help_text="List of items e.g. ['Trekking shoes', 'Warm jacket', 'Rain poncho']")),
                ('is_featured', models.BooleanField(default=False)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, max_length=150)),
                ('meta_description', models.CharField(blank=True, max_length=250)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='adventures.category')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='adventures.destination')),
            ],
            options={
                'ordering': ['ordering', '-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traveler_name', models.CharField(max_length=150)),
                ('traveler_location', models.CharField(blank=True, default='Bangalore, India', max_length=150)),
                ('avatar_url', models.CharField(blank=True, max_length=500)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('review_text', models.TextField()),
                ('travel_date', models.CharField(blank=True, default='October 2024', max_length=50)),
                ('is_verified', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='adventures.trip')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer', models.TextField()),
                ('category', models.CharField(default='General', help_text='e.g. Booking, Safety, Gear, Fitness', max_length=100)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='adventures.trip')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['ordering', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=25)),
                ('travel_date', models.CharField(blank=True, help_text='Preferred travel date or month', max_length=50)),
                ('travelers_count', models.PositiveIntegerField(default=1)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New Enquiry'), ('CONTACTED', 'Contacted'), ('FOLLOW_UP', 'Follow Up'), ('CONVERTED', 'Converted'), ('CLOSED', 'Closed')], default='NEW', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='adventures.trip')),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=500)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('is_cover', models.BooleanField(default=False)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='adventures.trip')),
            ],
            options={
                'ordering': ['ordering', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TripItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('altitude', models.CharField(blank=True, max_length=100)),
                ('distance', models.CharField(blank=True, max_length=100)),
                ('meals', models.CharField(default='Breakfast, Lunch, Dinner', max_length=150)),
                ('stay_type', models.CharField(default='Tented Camp / Alpine Tents', max_length=150)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_days', to='adventures.trip')),
            ],
            options={
                'verbose_name_plural': 'Trip Itineraries',
                'ordering': ['day_number', 'ordering'],
            },
        ),
        migrations.CreateModel(
            name='TripVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.CharField(max_length=500)),
                ('poster_image', models.CharField(blank=True, max_length=500)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='adventures.trip')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
    ]
