# Generated by Django 5.2.17 on 2026-09-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='departure_city',
            field=models.CharField(blank=True, default='Bengaluru', max_length=100),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='follow_up_date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High Priority'), ('MEDIUM', 'Medium Priority'), ('LOW', 'Low Priority')], default='MEDIUM', max_length=10),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('NEW', 'New Enquiry'), ('CONTACTED', 'Contacted'), ('FOLLOW_UP', 'Follow Up'), ('PAYMENT_PENDING', 'Payment Pending'), ('CONVERTED', 'Converted'), ('CLOSED', 'Closed')], default='NEW', max_length=20),
        ),
    ]
